---
name: rule1
pack: vm_action
description: Sample rule firing on vm_task_queue.event1.
enabled: true
trigger:
    type: vm_action.event1
action:
    ref: vm_action.vm_util1
    parameters:
        greeting: Yo